
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/cloud65?useSSL=false&useUnicode=true&characterEncoding=UTF-8&charset=utf8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        # 注意冒号后要空格，且放在 spring.cloud 下
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 9999
      web-context-unify: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  tomcat:
    threads:
      max: 10
  port: 8091
feign:
  sentinel:
    enabled: true
