server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product_route
          uri: lb://product
          predicates:
            - Path=/p/**
          filters:
            - StripPrefix=1
            - Time=true
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/o/**
          filters:
            - StripPrefix=1
            - Abc=1,2,hello,true,123
    sentinel:
      transport:
        dashboard: localhost:8858
        port: 9999
  redis:
    password: ''
